services:
  - type: web
    name: password-generator-hello-world
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        generateValue: true
    healthCheckPath: /health